baseURL = "https://2020.abrilnofeminino.pt/"
# baseURL = "https://clever-perlman-069d0d.netlify.com"
publishDir = "/var/www/2020.abrilnofeminino.pt"
languageCode = "pt-pt"
title = "Abril No Feminino"
theme = "abrilnofeminino"

resampleFilter = "lanczos"

# Defatult JPEG quality setting. Default is 75.
quality = 90

headerPhoto = "home_bg.jpg"

[taxonomies]
	tag = "tags"
	categoria = "categorias"
	ciclo = "ciclos"
[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = false
