baseURL = "https://abrilnofeminino.pt/"
languageCode = "pt-pt"
title = "Abril No Feminino"
theme = "abrilnofeminino"
publishdir = "public"

resampleFilter = "lanczos"

# Defatult JPEG quality setting. Default is 75.
quality = 90

headerPhoto = "home_bg.jpg"

[taxonomies]
	tag = "tags"
	categoria = "categorias"
	ciclo = "ciclos"